FROM node:20-alpine

WORKDIR /app

# Docker ichida Next.js hot-reload uchun polling zarur
ENV WATCHPACK_POLLING=true
ENV NEXT_TELEMETRY_DISABLED=1

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
